#!/usr/bin/env bash
# Install the pre-commit hook for papilov.org.
# Run once per clone: bash scripts/install-pre-commit.sh

set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_SRC="$REPO_ROOT/scripts/scan-private-refs.sh"
HOOK_DST="$REPO_ROOT/.git/hooks/pre-commit"

chmod +x "$HOOK_SRC"

cat >"$HOOK_DST" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-pre-commit.sh
# Do not edit directly — edit scripts/scan-private-refs.sh and re-run installer.
set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
exec bash "$REPO_ROOT/scripts/scan-private-refs.sh"
EOF

chmod +x "$HOOK_DST"

echo "✓ Pre-commit hook installed: $HOOK_DST"
echo "  It will scan staged changes in content/, static/, themes/ before every commit."
echo "  See scripts/scan-private-refs.sh for the regex and exceptions."
